references:
  install_imagemagick: &install_imagemagick
    run:
      name: Install ImageMagick
      command: sudo apt-get update && sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
  wait_for_postgres: &wait_for_postgres
    run:
      name: Wait for Postgres
      command: dockerize -wait tcp://localhost:5432 -timeout 1m
  setup: &setup
    run:
      name: Set up the environment
      command: bin/setup
  precompile_assets: &precompile_assets
    run:
      name: Precompile the assets
      command: bin/rails assets:precompile
  run_tests: &run_tests
    run:
      name: Run the test suite
      command: COVERAGE=true bin/rake

jobs:
  build:
    working_directory: ~/radfords
    docker:
      - image: "cimg/ruby:2.5-browsers"
        environment:
          PGHOST: localhost
          PGUSER: radfords
          RAILS_ENV: test
      - image: "cimg/postgres:14.4"
        environment:
          POSTGRES_USER: radfords
          POSTGRES_DB: radfords_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - <<: *install_imagemagick
      - <<: *wait_for_postgres
      - <<: *setup
      - <<: *precompile_assets
      - <<: *run_tests
